/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "brand-yellow": "#F6C453",
        "brand-yellow-light": "#FBE7A1",
        "brand-dark": "#1F1F1F",
        "brand-dark-sec": "#2A2A2A",
        "terminal-green": "#00ff41",
        "terminal-bg": "#050505",
        "terminal-panel": "#0e0e0e",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#cbc4d2",
        "surface-bright": "#fdf7ff",
        "on-tertiary-fixed": "#241a00",
        "tertiary-container": "#c9a74d",
        "on-primary-fixed": "#22005d",
        "error-container": "#ffdad6",
        "primary": "#4f378a",
        "on-surface": "#1d1b20",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-container": "#e0d2ff",
        "surface-container-high": "#ece6ee",
        "on-background": "#1d1b20",
        "surface-variant": "#e6e0e9",
        "surface-tint": "#6750a4",
        "error": "#ba1a1a",
        "tertiary": "#765b00",
        "primary-container": "#6750a4",
        "surface": "#fdf7ff",
        "background": "#F4F6F8",
        "tertiary-fixed-dim": "#e7c365",
        "on-secondary": "#ffffff",
        "outline": "#7a7582",
        "on-primary": "#ffffff",
        "inverse-surface": "#322f35",
        "tertiary-fixed": "#ffdf93",
        "surface-container-highest": "#e6e0e9",
        "inverse-primary": "#cfbcff",
        "primary-fixed": "#e9ddff",
        "on-secondary-fixed": "#1f1635",
        "on-primary-fixed-variant": "#4f378a",
        "surface-container": "#f2ecf4",
        "secondary-fixed": "#e9ddff",
        "primary-fixed-dim": "#cfbcff",
        "on-tertiary-fixed-variant": "#594400",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#cdc0e9",
        "on-secondary-container": "#645a7d",
        "surface-container-low": "#f8f2fa",
        "surface-dim": "#ded8e0",
        "on-tertiary-container": "#503d00",
        "on-surface-variant": "#494551",
        "inverse-on-surface": "#f5eff7",
        "secondary-container": "#e1d4fd",
        "secondary": "#63597c",
        "on-secondary-fixed-variant": "#4b4263",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "xl": "64px",
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "40px",
        "gutter": "24px",
        "container_margin": "32px",
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "code-sm": ["Courier New", "monospace"],
        "headline-md": ["Courier New", "monospace"],
        "body-md": ["Courier New", "monospace"],
        "body-lg": ["Courier New", "monospace"],
        "headline-lg": ["Courier New", "monospace"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "subheading": ["20px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-xl": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "400" }],
        "headline-md-term": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
